### ISSUE TITLE
Invalid result https://tryhackme.com/p/poizon_nvkz

### ISSUE THREAD

**Issue by Dreamer0iQ** [soxoj/maigret#1030]
Invalid link: <https://tryhackme.com/p/poizon_nvkz>

- [x ] I'm sure that the link leads to "not found" page

**Comment by Dreamer0iQ** [comment]
This links too:

<http://www.skodaforum.ru/member.php?username=poizon_nvkz>

<https://opencollective.com/poizon_nvkz>

<https://boosty.to/poizon_nvkz>

**Comment by MeowyPouncer** [comment]
All of the given sites either work or were disabled due to being down.
