### ISSUE TITLE
Feature Request: sort by number of data points

### ISSUE THREAD

**Issue by maximousblk** [soxoj/maigret#105]
It would be better if the exported reports (atleast pdf and html) were sorted by the number of data points from the sources. So the important results are at the top and the ones that do not have any info are at the bottom.

**Comment by soxoj** [comment]
Hey, thank you for the great idea! How do you think, will it be convenient to make a separate CLI option?

**Comment by maximousblk** [comment]
Yeah that could work.

```sh
maigret <username> --sort [ rank | data ]
```

**Comment by soxoj** [comment]
Hey, I've implemented this feature as an option `--reports-sorting data`.
