### ISSUE TITLE
Invalid result https://tieba.baidu.com/home/main?un=gymicon

### ISSUE THREAD

**Issue by IconicLLL** [soxoj/maigret#1108]
Invalid link: <[Invalid?](https://github.com/soxoj/maigret/issues/new?assignees=soxoj&labels=bug&template=report-false-result.md&title=Invalid%20result%20https://tieba.baidu.com/home/main?un=gymicon)Photo>

- [ ] I'm sure that the link leads to "not found" page

**Comment by MeowyPouncer** [comment]
The username exists at the moment.
