### ISSUE TITLE
Invalid result http://archive.org/wayback/available?url=https://twitter.com/arielreises/status/*

### ISSUE THREAD

**Issue by arielreises** [soxoj/maigret#1147]
Invalid link: http://archive.org/wayback/available?url=https://twitter.com/arielreises/status/*

- [x] I'm sure that the link leads to "not found" page

**Comment by MeowyPouncer** [comment]
Well, it mightn't be obvious, but the given page points to the existence of the username being checked. The ending asterisk belongs to the URL.
