### ISSUE TITLE
Test failure: `test_import_aiohttp_cookies`

### ISSUE THREAD

**Issue by Laura7089** [soxoj/maigret#1383]
## Checklist

- [x] I'm reporting a bug in Maigret functionality
- [x] I've checked for similar bug reports including closed ones
- [x] I've checked for pull requests that attempt to fix this bug

## Description

Test `test_import_aiohttp_cookies` fails.

Info about Maigret version you are running and environment (`--version`, operation system, ISP provider):
First encountered when installing v0.4.4 from the AUR on Arch Linux.

How to reproduce this bug (commandline options / conditions):
`pytest`

```
___________________________ test_import_aiohttp_cookies ____________________________

    @pytest.mark.asyncio
    async def test_import_aiohttp_cookies():
        cookies_filename = 'cookies_test.txt'
        with open(cookies_filename, 'w') as f:
            f.write(COOKIES_TXT)

        cookie_jar = import_aiohttp_cookies(cookies_filename)
>       assert list(cookie_jar._cookies.keys()) == ['xss.is', 'httpbin.org']
E       AssertionError: assert [('xss.is', '...in.org', '/')] == ['xss.is', 'httpbin.org']
E         At index 0 diff: ('xss.is', '/') != 'xss.is'
E         Use -v to get more diff

tests/test_activation.py:44: AssertionError
```

**Comment by soxoj** [comment]
Thanks, @Laura7089! It was an error due to a new version of aiohttp. It's fixed now.
