### ISSUE TITLE
Invalid result https://vk.com/prolabsix

### ISSUE THREAD

**Issue by Sub62Kkkkkkkkkkkk** [soxoj/maigret#1512]
Invalid link: <INSERT LINK HERE>

- [ ] I'm sure that the link leads to "not found" page

**Comment by rly0nheart** [comment]
Hey @Sub62Kkkkkkkkkkkk, that link seems to be valid

![Screenshot 2024-05-14 at 02-33-08 Sergey Sergeevich](https://github.com/soxoj/maigret/assets/74001397/32a82d11-2684-4dd1-a277-7fd2ca84f302)
