### ISSUE TITLE
Invalid result https://www.allrecipes.com/cook/GULENISH11

### ISSUE THREAD

**Issue by Vstya** [soxoj/maigret#1519]
https://www.allrecipes.com/cook/GULENISH11
https://www.shutterstock.com/fi/g/GULENISH11/about
https://linktr.ee/GULENISH11
https://music.yandex.ru/users/GULENISH11/playlists
https://lolchess.gg/profile/na/GULENISH11
https://imginn.com/tagged/GULENISH11/
Invalid link: <INSERT LINK HERE>

- [x] I'm sure that the link leads to "not found" page

**Comment by rly0nheart** [comment]
Hey @Vstya, the following sites have been fixed:

* AllRecipes
* Shutterstock
* Linktree
* ImgInn

The following have been disabled:
* Lolchess.gg

I'll take a look at music.yandex.ru, and update you. See pull request #1517 for more information on fixed and disabled sites
