### ISSUE TITLE
Invalid result https://t.me/Mevusxz

### ISSUE THREAD

**Issue by Hezeci** [soxoj/maigret#1521]
Invalid link: <INSERT LINK HERE>

- [x] I'm sure that the link leads to "not found" page

**Comment by rly0nheart** [comment]
Hey @Hezeci, the url is valid, maybe this was a temporary issue on Telegram's end? There's also a new issue that is similar #1530 

![Screenshot 2024-05-14 at 02-27-59 ~× люцифер🍷×°](https://github.com/soxoj/maigret/assets/74001397/2ae6c5b2-976a-4008-9440-f1b681887862)
