### ISSUE TITLE
Invalid result https://fozo.info/user/Caitlindayxx/

### ISSUE THREAD

**Issue by Janslooe** [soxoj/maigret#1523]
Invalid link: <[>](https://fozo.info/user/Caitlindayxx/)

- [x] I'm sure that the link leads to "not found" page

**Comment by rly0nheart** [comment]
Hey mate, it seems the site is offline. Might need to keep an eye on it and see how long it will be down.

![Screenshot 2024-05-14 at 02-25-53 The site is temporarily offline](https://github.com/soxoj/maigret/assets/74001397/ef6a5335-1664-4235-ad06-328f930b6c24)
