### ISSUE TITLE
Invalid result https://t.me/fIuffyly

### ISSUE THREAD

**Issue by Guvbjfv** [soxoj/maigret#1530]
Invalid link: <INSERT LINK HERE>

- [x] I'm sure that the link leads to "not found" page

**Comment by rly0nheart** [comment]
Hey @Guvbjfv, that link seems valid to me

![Screenshot 2024-05-14 at 02-23-51 ࣪ ৎ ɸᴧуᴩя!¡◠ 1100](https://github.com/soxoj/maigret/assets/74001397/1b41e8a7-0f5e-405c-bde3-159e04e6a38f)
