### ISSUE TITLE
Documentation issue noticed.

### ISSUE THREAD

**Issue by Lord-Topa** [soxoj/maigret#1544]
## Checklist

- [ x] I'm reporting a bug in Maigret functionality
- [ x] I've checked for similar bug reports including closed ones
- [ ] I've checked for pull requests that attempt to fix this bug

## Description
Hey y'all this isn't actually necessarily a functionality problem but rather a documentation problem. When attempting to follow along with the tutorial on the main github page (the animated one) the code does not function because of the way that argument handling seems to have been changed. 

How to reproduce this bug (commandline options / conditions):
Simply view the github project's homepage and attempt to follow along with the animated portion.

**Comment by soxoj** [comment]
Hi, thank you, you’re absolutely right. We'll fix it shortly.

**Comment by soxoj** [comment]
Fixed.
