### ISSUE TITLE
Invalid result https://www.figma.com/@asal_tew

### ISSUE THREAD

**Issue by Arastooanan** [soxoj/maigret#1613]
Invalid link: <INSERT LINK HERE>

- [x] I'm sure that the link leads to "not found" page

**Comment by Arastooanan** [comment]
Invalid link: <INSERT LINK HERE>



- [ ] I'm sure that the link leads to "not found" page

**Comment by soxoj** [comment]
This site check was disabled in #1928, no longer functioning due to Cloudflare
