### ISSUE TITLE
Invalid result https://music.yandex.ru/users/criska1/playlists

### ISSUE THREAD

**Issue by Sigma999000** [soxoj/maigret#1626]
Invalid link: <INSERT LINK HERE>

- [x] I'm sure that the link leads to "not found" page

**Comment by Sigma999000** [comment]
че блять

Пн, 25 нояб. 2024 г. в 22:30, Soxoj ***@***.***>:

**Comment by soxoj** [comment]
Проблема закрыта, проверка по этому сайту будет отключена.
