### ISSUE TITLE
Incompatible version requirements

### ISSUE THREAD

**Issue by congaterori** [soxoj/maigret#177]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flask 2.0.1 requires Jinja2>=3.0, but you have jinja2 2.11.3 which is incompatible.
but I see in requirements.txt is Jinja2==2.11.3

**Comment by congaterori** [comment]
run in replit
ERROR: pyquil 1.9.0 requires typing>=3.6, which is not installed.
ERROR: python-language-server 0.31.10 has requirement jedi<0.16,>=0.14.1, but you'll have jedi 0.18.0 which is incompatible.
ERROR: flask 2.0.1 has requirement Jinja2>=3.0, but you'll have jinja2 2.11.3 which is incompatible.
ERROR: dephell 0.8.3 has requirement pip<=19.3.1,>=18.0, but you'll have pip 21.1.3 which is incompatible.

**Comment by soxoj** [comment]
Could you make a PR if you have already resolved the issue with requirements.txt fixes?

**Comment by soxoj** [comment]
@congaterori please, make a pull request from your fork.

**Comment by JasperJuergensen** [comment]
I got the same problem Problem with attrs. Installed is 20.3.0, needed is 21.2.*
I opened PR #196 which updates both versions.

**Comment by soxoj** [comment]
@JasperJuergensen great, big thanks!

**Comment by soxoj** [comment]
I checked run in Replit, all the Maigret requirements conflicts was resolved.
