### ISSUE TITLE
How does it differ from sherlock?

### ISSUE THREAD

**Issue by divinity76** [soxoj/maigret#1819]
What's the point of the fork? how does it differ from sherlock? are sherlock improvements being backported to maigret? are maigret improvements being sent to sherlock?

Would be nice if the README made it more clear

(sorry for labeling it `bug` - there was no label for `documentation` and I had to pick one)

**Comment by soxoj** [comment]
Hi! Thanks for your question.

This fork was created during a period of inactivity in Sherlock’s development. Some core logic changes I proposed in a PR to Sherlock were not accepted, so I decided to create this fork.

Currently, there are significant differences between the two projects, both in the site database and in their philosophies. Sherlock is a lightweight program, while Maigret has many dependencies to enable deeper searches, account information extraction from sites, export to various report formats, and more.

As a result, backports are not planned. However, Maigret is MIT-licensed, so anyone is free to use its site database or implement its features.

P.S. The `documentation` label does exist—strangely, you didn’t see it. :)
