### ISSUE TITLE
New logo ?

### ISSUE THREAD

**Issue by ocervell** [soxoj/maigret#1867]
Our logo is old, pixellated and blurry.

Could we make a better one ?

Here are some new examples of what could be done using AI:
![image](https://github.com/user-attachments/assets/2d7024a0-09e8-4cb3-ba5d-ea8adedc65a1)
![image](https://github.com/user-attachments/assets/03149201-2202-4013-9d54-68dd34e0ae75)
![image](https://github.com/user-attachments/assets/9ccaf418-695a-4f38-89cd-f59915625360)

**Comment by soxoj** [comment]
Hi @ocervell, thanks a lot, I'll update it! Could you try to create another one with a silhouette that resembles Jules Maigret more closely?

**Comment by ocervell** [comment]
Here are some more:
![file-MqcXwmi4uV9Dr7RjYd18aN (2).png](https://github.com/user-attachments/assets/a165a210-2a5c-4658-9bed-1fe20e341dc2)

![file-DU49qCZqvrJRJc9J8wfeXg.png](https://github.com/user-attachments/assets/e712b239-45c3-4cc3-80a4-8d6f8d07a0f6)

![file-LXAevxkqLkYJTuGzFukJoN.png](https://github.com/user-attachments/assets/fb9214ad-415e-4e03-84ca-54f1b82a837c)

![file-8c1rPVJwUKvb8aSKsvS19h.png](https://github.com/user-attachments/assets/7847ddbe-a532-4cf2-ad23-aeda94a508fc)

![file-4M4rQNm5fzoPGpN6pcHNVq.png](https://github.com/user-attachments/assets/24e73b9a-b9e4-40cb-b9ae-5438add70b66)

![file-9GKQMmu2u4QdXCxjL5q4wq.png](https://github.com/user-attachments/assets/57579b41-5aee-42ea-8ec6-e03e88e70ed4)

![file-LnyFyKtUzKFMpiMJyeZgXg.png](https://github.com/user-attachments/assets/27231706-0708-4c44-89a8-6699f4e6da13)

![file-1sM8NTXbA7TexxzRdVnjv3.png](https://github.com/user-attachments/assets/fa7afc17-ef00-4fa5-96d4-7ced9dd4ef39)

**Comment by soxoj** [comment]
That's amazing, thanks! Could you send me the original version directly, as a file? As I understand it, GitHub compresses the image, and it loses quality.

**Comment by ocervell** [comment]
https://i.postimg.cc/mgqcjmGB/file-H9a-Gvzf-S5-Lkpjy-N3q9-UH43-2.png

**Comment by ocervell** [comment]
Look amazing !!
