### ISSUE TITLE
Pass `tzinfos` argument in order to correctly return a timezone-aware datetime

### ISSUE THREAD

**Issue by GreenAA** [soxoj/maigret#1904]
Hi thanks for excellent app 

i get error 

Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.

## Checklist

- [ ] I'm reporting a bug in Maigret functionality
- [ ] I've checked for similar bug reports including closed ones
- [ ] I've checked for pull requests that attempt to fix this bug

## Description

Info about Maigret version you are running and environment (`--version`, operation system, ISP provider):
<INSERT VERSION INFO HERE>

How to reproduce this bug (commandline options / conditions):
<INSERT EXAMPLE OF CLI COMMAND HERE>

<DESCRIPTION>

<PASTE SCREENSHOT>

<ATTACH LOG FILE>

**Comment by soxoj** [comment]
Hi, thanks for the report!

Could you clarify where you want to pass `tzinfos` and where you expect to see the changes?
A use case description would help understand what needs to be adjusted.

**Comment by soxoj** [comment]
It is the same problem as in #454?

**Comment by GreenAA** [comment]
I answer later,  now I'm  out

**Comment by GreenAA** [comment]
hi 
please sea the clip 

https://streamable.com/zyxutq

i have vs  code  , i try run with anconda  i try some names user and get same error 

i can't know where to move the tzinfos 

meybe i wrong all ok ... if you can check 


thanks .. wow app

**Comment by soxoj** [comment]
Thanks! I've fixed it, please, install the development version:
1. Download https://github.com/soxoj/maigret/archive/refs/heads/main.zip
2. Unzip archive
3. Make `pip install .` from the unzipped directory

**Comment by GreenAA** [comment]
wow bro   you the excellent , thanks
