### ISSUE TITLE
sites.md missing

### ISSUE THREAD

**Issue by mxrch** [soxoj/maigret#20]
I've seen you deleted the sites.md file that list all the supported sites, but in the readme there is always the line `Currently supported more than 1500 sites (full list).` with this link :
`https://github.com/soxoj/maigret/blob/main/sites.md` which redirects to nothing.

**Comment by soxoj** [comment]
Thanks, I deleted it by mistake. Will restore it!

**Comment by soxoj** [comment]
Restored by commit 21f4485e9ab2266bd28d3cd215712c72054d6478.
