### ISSUE TITLE
Invalid result https://www.twitch.tv/Hyze666

### ISSUE THREAD

**Issue by Manyna22** [soxoj/maigret#267]
Invalid link: <INSERT LINK HERE>
Invalid result https://www.twitch.tv/Hyze6

**Comment by soxoj** [comment]
Hey, I don't see problems with checking Hyze666 for now.
https://www.twitch.tv/Hyze666
![image](https://user-images.githubusercontent.com/31013580/145859904-8856be58-a40f-4f80-bf3b-c61fcf567a65.png)

Why do you treat it is invalid?

**Comment by soxoj** [comment]
I'll close it without feedback from you.
