### ISSUE TITLE
Invalid result https://t.me/likhhukd

### ISSUE THREAD

**Issue by grindernlm** [soxoj/maigret#284]
Invalid link: <INSERT LINK HERE>

- [x] I'm sure that the link leads to "not found" page

**Comment by soxoj** [comment]
Hi, I see that profile really exists. Could you explain your issue?

![image](https://user-images.githubusercontent.com/31013580/147885057-eee2853a-6bc9-42db-9596-ed5d16179e55.png)

**Comment by soxoj** [comment]
Close the issue
