### ISSUE TITLE
The "AttributeError" appearance

### ISSUE THREAD

**Issue by ElFanzo** [soxoj/maigret#3]
![Снимок](https://user-images.githubusercontent.com/12198644/91660904-024ff080-eaf2-11ea-8d8d-3be02c36b5ac.PNG)

UPD: works after rerun

**Comment by soxoj** [comment]
Thank you, @ElFanzo! Fix this problem [here](https://github.com/soxoj/maigret/commit/60b253571f96a0d32f0f090eef52907bc4e7b6ec#diff-8f8e8426e48bf1c37d52b02ca11983deR360).
