### ISSUE TITLE
Invalid result https://yandex.ru/collections/api/users/Volfcub71/

### ISSUE THREAD

**Issue by Alexdmitr2099** [soxoj/maigret#324]
Invalid link: <INSERT LINK HERE>

- [x] I'm sure that the link leads to "not found" page

**Comment by soxoj** [comment]
I see that profile exists. Could you attach a screenshot or text response by URL from your side? 
![image](https://user-images.githubusercontent.com/31013580/150397144-56679708-9636-428d-aef9-4e1597edcceb.png)

**Comment by soxoj** [comment]
Close the issue
