### ISSUE TITLE
Invalid result https://www.wikipedia.org/wiki/User:behzad_nikzad

### ISSUE THREAD

**Issue by blombery13** [soxoj/maigret#361]
Invalid link: <INSERT LINK HERE>

- [x] I'm sure that the link leads to "not found" page

**Comment by soxoj** [comment]
Thank you, I'll fix it

**Comment by soxoj** [comment]
Fixed in [6a03aff](https://github.com/soxoj/maigret/pull/365/commits/6a03affa855aa8decb94f431a2ee9556c5844c88)

**Comment by blombery13** [comment]
tnx

در تاریخ شنبه ۲۶ فوریهٔ ۲۰۲۲،‏ ۱۴:۵۸ Soxoj ***@***.***> نوشت:
