### ISSUE TITLE
Invalid result https://yandex.ru/collections/api/users/Hmdaler/

### ISSUE THREAD

**Issue by zahir1965** [soxoj/maigret#381]
Invalid link: <INSERT LINK HERE>

- [ ] I'm sure that the link leads to "not found" page

**Comment by cyb3rk0tik** [comment]
Strange, but I got the result for this username in this service.

Try update maigret
**pip install -U maigret**
and run this command:
**maigret --site "YandexCollections API" Hmdaler**

**Comment by soxoj** [comment]
Close due to no updates
