### ISSUE TITLE
Invalid result https://vk.com/bringer1984

### ISSUE THREAD

**Issue by Bezdna9** [soxoj/maigret#398]
Invalid link: <INSERT LINK HERE>

- [x] I'm sure that the link leads to "not found" page

**Comment by cyb3rk0tik** [comment]
@Bezdna9
This page are available:

>    [*] Checking username bringer1984 on:
>    [+] VK: https://vk.com/bringer1984
>    └─fullname: Андрей Зияев
>    [+] VKFaces [VK]: https://vkfaces.com/vk/user/bringer1984

If you have old version maigret update it:
`pip install maigret -U`

And check again.

**Comment by soxoj** [comment]
Close due to no updates
