### ISSUE TITLE
https://vk.com/bringer1984

### ISSUE THREAD

**Issue by Bezdna9** [soxoj/maigret#399]
Link to the site main page: https://example.com
Link to an existing account: https://example.com/users/john
Link to a nonexistent account: https://example.com/users/noonewouldeverusethis7
Tags: photo, us, ...

**Comment by cyb3rk0tik** [comment]
@Bezdna9 
This page are available:
> [*] Checking username bringer1984 on:
> [+] VK: https://vk.com/bringer1984
>  └─fullname: Андрей Зияев
> [+] VKFaces [VK]: https://vkfaces.com/vk/user/bringer1984

If you have old version maigret update it:
`pip install maigret -U`

And check again.
