### ISSUE TITLE
Invalid result https://www.techdirt.com/user/<insertwhatyouwant>

### ISSUE THREAD

**Issue by bashinho** [soxoj/maigret#405]
Invalid link: [<INSERT LINK HERE>](https://www.techdirt.com/user/asölkdfjaölsdjkfaäsldkfjaäskdfjaäsjdf)

- [x] I'm sure that the link leads to "not found" page
it is not really an not found page which says not found, it just shows everytime the same page. does not matter which "username" you give

**Comment by antomarsi** [comment]
Looks like the page redirect to the main page, i think the fix is making this change:
```
    "checkType": "message",
    "absenceStrs": "<ul id='profilenav'",
```

**Comment by cyb3rk0tik** [comment]
> Looks like the page redirect to the main page, i think the fix is making this change:
> 
> ```
>     "checkType": "message",
>     "absenceStrs": "<ul id='profilenav'",
> ```
For the string present, you have to use presenseStrs field. There is also a little problem with double quotes, i took just word "profilenav".

But thank you for the tip!
