### ISSUE TITLE
Invalid result http://forum.vegalab.ru/member.php?username=denamn29

### ISSUE THREAD

**Issue by userdev01rgithub** [soxoj/maigret#485]
Invalid link: <INSERT LINK HERE>

- [x] I'm sure that the link leads to "not found" page

**Comment by fen0s** [comment]
works fine for me, denamn29 account doesn't exist and maigret says it doesn't exist too

`python maigret.py denamn29 --site vegalab
[-] Starting a search on top 1 sites from the Maigret database...
[!] You can run search by full list of sites with flag `-a`
[*] Checking username denamn29 on:
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.11it/s]
[*] Short text report:
Search by username denamn29 returned 0 accounts.
Extended info extracted from 0 accounts.`
