### ISSUE TITLE
Invalid result https://eva.ru/passport/yashwardhan333666/profile.htm

### ISSUE THREAD

**Issue by yashwardhan333666** [soxoj/maigret#537]
Invalid link: <https://eva.ru/passport/yashwardhan333666/profile.htm>

- [x] I'm sure that the link leads to "not found" page

**Comment by fen0s** [comment]
we couldn't really find the way, or find registration/valid profiles here, so i'll leave the site disabled and close the issue
feel free to tag me for reopening if you consider this decision wrong
