### ISSUE TITLE
Invalid result https://t.me/nemka_blin

### ISSUE THREAD

**Issue by Owerwill** [soxoj/maigret#541]
Invalid link: <INSERT LINK HERE>

- [ ] I'm sure that the link leads to "not found" page

**Comment by fen0s** [comment]
what's the invalid result? the result is valid for me, it found according tg channel
`[-] Starting a search on top 2 sites from the Maigret database...
[!] You can run search by full list of sites with flag `-a`
[*] Checking username nemka_blin on:
[+] Telegram: https://t.me/nemka_blin
 ├─fullname: 𝐥𝐞𝐜𝐤 𝐧𝐞𝐦𝐤𝐚 🕷
 ├─image: https://cdn4.telegram-cdn.org/file/tBae8kPJP2IkE4SF-GmliZexIaAeI9dY0Oi9AnxP6SIfbqrMyiFjwTjNy2bL9Xa4xlb8X6bev1Tb2ew5OGnjCJ1Lh3NhEu4epg06_2fkyTbF24KjIXGLppEgmoZiPQTyqju59ox5g2-CO3xf9HuPCKN4F9uxz0dEk4hK-zJg3fXxP4o_hqX_dScAQ0s1SAoTUjaH-osHCMsPQk9xlhHrHd9AcJxGxa5Gvw_U83TfIs_Ur15Z86n-BkvDw8KQZ0NcjOWYTkm50AEiSImEkVjXouLYOsgaNfWsthkxFWUAldxCaObNww5XFhs4Ixe_JMSYVhiki2Vmkgnfh74ig0QnhQ.jpg
 └─bio: люблю лерку🤍💗
100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.15s/it]
[-] Restarting checks for 1 sites... (1 attempts left)
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.23s/it]
[!] Too many errors of type "Connecting failure" (50.0%)
[-] You can see detailed site check errors with a flag `--print-errors`
[*] Short text report:
Search by username nemka_blin returned 1 accounts.
Extended info extracted from 1 accounts.
Interests (tags): messaging`
