### ISSUE TITLE
Too much errors cause report not being generated

### ISSUE THREAD

**Issue by EDM115** [soxoj/maigret#545]
## Checklist

- [x] I'm reporting a bug in Maigret functionality
- [ ] I've checked for similar bug reports including closed ones
- [x] I've checked for pull requests that attempt to fix this bug

## Description
  
Info about Maigret version you are running and environment (`--version`, operation system, ISP provider):
<INSERT VERSION INFO HERE>
```
__main__.py 0.4.3  
Socid-extractor:  0.0.23  
Aiohttp:  3.8.1  
Requests:  2.27.1  
Python:  3.10.1
```
  
How to reproduce this bug (commandline options / conditions):
`python -m maigret edm115 -a -v -H -P`
   
I tried it, but the report didn't showed up  
  
*Screenshot : None*
  
[https://bayfiles.com/59MbD0xeyb/maigret-logs_txt](https://bayfiles.com/59MbD0xeyb/maigret-logs_txt)

**Comment by fen0s** [comment]
i couldn't reproduce the bug, html report did generate for me in the end
what system are you using? and could you accidentally cancel the search early hitting ctrl+c?

**Comment by EDM115** [comment]
Windows 10 (don't have precise version tho, as I'm on phone now)  
32 bit os  
asus x205ta

**Comment by EDM115** [comment]
and I didn't Ctrl-C  
process were just running, while I did other things out of my computer

**Comment by fen0s** [comment]
> and I didn't Ctrl-C process were just running, while I did other things out of my computer

 yeah, i pinpointed the issue, apparently it was unicode decoding error
i notified Soxoj, main dev, about this, let's see how we can fix this
