### ISSUE TITLE
error when generating report

### ISSUE THREAD

**Issue by tiffanyadams2** [soxoj/maigret#563]
## Checklist

- [ ] I'm reporting a bug in Maigret functionality
- [ ] I've checked for similar bug reports including closed ones
- [ ] I've checked for pull requests that attempt to fix this bug

## Description

Info about Maigret version you are running and environment (`--version`, operation system, ISP provider):
maigret 0.4.3
Socid-extractor:  0.0.23
Aiohttp:  3.8.1
Requests:  2.28.1
Python:  3.10.5

How to reproduce this bug (commandline options / conditions):
maigret user1 user2 user3 user4 --html

I get an error (two ??) when it's time to generate the report file. It only happens when there is more than one username, but sometimes it's ok. Can also happen when there is also a recursive username

![](https://user-images.githubusercontent.com/109771237/180334364-24b99754-cf0e-47ca-8fd3-6e03caf1526d.png)

**Comment by fen0s** [comment]
this is a known error with unicode encoding, we're fixing it rn, next pr should make things fine
