### ISSUE TITLE
Currently my bot can only tell [super]group ID if added to the group. However if a supergroup admin posted any message anonymously, the bot can tell supergroup's ID.

### ISSUE THREAD

**Issue by Qaz1235wsx** [soxoj/maigret#588]
Currently my bot can only tell [super]group ID if added to the group. However if a supergroup admin posted any message anonymously, the bot can tell supergroup's ID. 

Need to implement this.

__Originally posted by @MasterGroosha in https://github.com/MasterGroosha/my-id-bot/issues/15__

**Comment by soxoj** [comment]
Not related for Maigret
