### ISSUE TITLE
Docker image for ARM

### ISSUE THREAD

**Issue by krydos** [soxoj/maigret#676]
Hey there, 
my apologies it is not a "Add a site" type of an issue, I wasn't sure what option to choose. 

I've built an ARM64 image - https://hub.docker.com/r/krydos/maigret
I'm not sure how to transfer it to your account though... Do you know any way to do it?
If you have any capabilities to build it yourself I'll highly appreciate that and remove my build. 

I'm on M1 mac and I really wanted to quickly try the tool by using docker but it didn't work because maigret image is built for amd64 only.

**Comment by soxoj** [comment]
Hey @krydos, thanks! We can add link to your image to README and [the documentation](https://maigret.readthedocs.io/), but I ask you first link your github fork of Maigret to the DockerHub and setup auto-builds [this way](https://github.com/soxoj/maigret/blob/main/.github/workflows/build-docker-image.yml).

It's necessary for transparency cause it's potentially unknown what code is in the manually builded image.

**Comment by krydos** [comment]
hey @soxoj, 
thanks for the tips.
I've been trying to do it until I realized that with this approach it's going to build amd64 arch anyway because I'm not going to build it anymore and I delegate it to github. 

So I had to find a way how to build for arm using github actions and I guess I found it (see attached PR). 

I think you can just merge that pull request and after that you will get multi platform build that should work. There is no need in readme or docs updates.

**Comment by soxoj** [comment]
Great! I'll merge it

**Comment by soxoj** [comment]
Successfuly pushed to dockerhub, can you check image?

**Comment by krydos** [comment]
Just checked. Docker automatically pulled the proper arch.
Also works with podman. 

Perfect! Thanks!
