### ISSUE TITLE
Invalid results (6 sites, any username, including youtube)

### ISSUE THREAD

**Issue by biran4454** [soxoj/maigret#696]
Invalid links (* is any username):
- https://www.youtube.com/*
- https://manifold.markets/*
- https://www.lightstalking.com/author/*/
- https://stripchat.global/*
- http://*.yelp.com/
- https://www.influenster.com/*

These link to "not found" pages, the main page, or random articles.

edit: I'm using the latest version of maigret through google cloud shell, just running it on my own username.

**Comment by fen0s** [comment]
thanks, all of those are going to be fixed soon!
