### ISSUE TITLE
Export xmind

### ISSUE THREAD

**Issue by shadowdevnotreal** [soxoj/maigret#712]
1st = love this tool.
It is by far the gold standard for docier reporting.

I saw your parsing code and had a question maybe you can help me on.
You have one of the only tools I have seen that can successfully export into html, pdf, xmind, json, etc.

I would like to add that xmind & json export code to my own tool.
Can you please guide me on how I can take that code and add it to my OSINT tool........please.

I am a new developer and working on a universal import, export OSINT reporting tool, but cannot figure out how to clip that parsing code to make it work with my tool

**Comment by soxoj** [comment]
Hi, so what the problem use my code for export?
