### ISSUE TITLE
Invalid result

### ISSUE THREAD

**Issue by mongolito12345** [soxoj/maigret#729]
Invalid link: https://somethingdoesnotexist.yelp.com/

- [x] I'm sure that the link leads to "not found" page

Likely a Yelp update which change the detection method for unassigned username.

**Comment by fen0s** [comment]
yep, as i can see, it uses user ids now, i.e. https://www.yelp.com/user_details?userid=lZ6AwE7nQxRjkxRKenMD7w

sadly have to disable this in next update
