### ISSUE TITLE
Function docstring refers repo wiki

### ISSUE THREAD

**Issue by Siddhesh-Agarwal** [soxoj/maigret#791]
## Checklist

- [x] I'm reporting a bug in Maigret functionality
- [x] I've checked for similar bug reports including closed ones
- [x] I've checked for pull requests that attempt to fix this bug

## Description

A function docstring contains a link to the repositories wiki which doesn't exist. [Link to line](https://github.com/soxoj/maigret/blob/b4e963b2b1f8fe2c554d18792801e7a280cc6107/maigret/checking.py#LL607C31-L607C69)

**Comment by soxoj** [comment]
Fixed, thank you
