### ISSUE TITLE
Invalid results

### ISSUE THREAD

**Issue by luciodaou** [soxoj/maigret#830]
Got Invalid links for all these sites while checking for some of my real random usernames: 
https://www.strava.com/athletes/myusername
https://tjournal.ru/search/v2/subsite/relevant?query=myusername
https://www.donationalerts.com/r/myusername
https://trashbox.ru/users/myusername/
https://fancy.com/myusername
https://forum.vegalab.ru/member.php?username=myusername
https://onanistov.net/search.php?keywords=&terms=all&author=myusername
https://manifold.markets/myusername
https://www.mbclub.ru/forum/members/?username=myusername
https://forum-b.ru/search.php?action=search&keywords=&author=myusername
https://movie-forum.co/member.php?username=myusername
https://forum.vilo4nik.net/members/?username=myusername
http://www.skodaforum.ru/member.php?username=myusername
https://forum.yapisal.net/u/myusername
https://create.arduino.cc/projecthub/myusername

- [ X ] I'm sure that the link leads to "not found" page

**Comment by dezort12** [comment]
Thank you!
