### ISSUE TITLE
Invalid result for `Mastodon`, `FourSquare`, `Pinterest`, and `Facebook`

### ISSUE THREAD

**Issue by therealchiendat** [soxoj/maigret#848]
Invalid links: 
* https://chaos.social/@this.is.a.random.something
* https://mastodon.social/@this.is.a.random.something
* https://social.tchncs.de/@this.is.a.random.something
* https://ru.foursquare.com/this.is.a.random.something
* https://www.pinterest.com/this.is.a.random.something
* https://www.facebook.com/this.is.a.random.something

- [x] I'm sure that the link leads to "not found" page

### Description: 
Hello there 👋 ,

I tried to check for a random username called: `this.is.a.random.something` and I got a bunch of invalid results as seen bellow I used the `isFound()` method to determine the accounts.

Most of the invalid links seems to be part of the decentralized social network powered by [Mastodon](https://joinmastodon.org/).

Here is a parsed result from my end:

```
[
    {'site': 'chaos.social', 'username': 'this.is.a.random.something', 'profile_url': 'https://chaos.social/@this.is.a.random.something', 'location': None, 'follower_count': 0, 'following_count': 0, 'created_at': None, 'avatar_url': None, 'full_name': None, 'country': None, 'is_verified': None}, 
    {'site': 'mastodon.social', 'username': 'this.is.a.random.something', 'profile_url': 'https://mastodon.social/@this.is.a.random.something', 'location': None, 'follower_count': 0, 'following_count': 0, 'created_at': None, 'avatar_url': None, 'full_name': None, 'country': None, 'is_verified': None}, 
    {'site': 'social.tchncs.de', 'username': 'this.is.a.random.something', 'profile_url': 'https://social.tchncs.de/@this.is.a.random.something', 'location': None, 'follower_count': 0, 'following_count': 0, 'created_at': None, 'avatar_url': None, 'full_name': None, 'country': None, 'is_verified': None}, 
    {'site': 'Foursquare', 'username': 'this.is.a.random.something', 'profile_url': 'https://ru.foursquare.com/this.is.a.random.something', 'location': None, 'follower_count': 0, 'following_count': 0, 'created_at': None, 'avatar_url': None, 'full_name': None, 'country': None, 'is_verified': None}, 
    {'site': 'Pinterest', 'username': 'this.is.a.random.something', 'profile_url': 'https://www.pinterest.com/this.is.a.random.something/', 'location': None, 'follower_count': 0, 'following_count': 0, 'created_at': None, 'avatar_url': None, 'full_name': None, 'country': None, 'is_verified': None}, 
    {'site': 'Facebook', 'username': 'this.is.a.random.something', 'profile_url': 'https://www.facebook.com/this.is.a.random.something', 'location': None, 'follower_count': 0, 'following_count': 0, 'created_at': None, 'avatar_url': None, 'full_name': None, 'country': None, 'is_verified': None}
]
```
### Screenshots:
The screenshots are taken when the links are clicked:

<img width="1188" alt="image" src="https://user-images.githubusercontent.com/44085158/217619789-72458cc5-b127-47b6-b2b7-a04bd4b6648e.png">
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/44085158/217619884-6a763acf-5aa4-45c8-be32-856bfc04fc59.png">
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/44085158/217619939-5a050d30-72d4-4650-8160-c3987c1f16ea.png">
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/44085158/217620201-3eda0e3d-8508-46e6-8ea7-8e110c63f175.png">
<img width="1459" alt="image" src="https://user-images.githubusercontent.com/44085158/217620253-5d5f03d3-7a34-4108-b8e8-6179fdde1427.png">
<img width="1496" alt="image" src="https://user-images.githubusercontent.com/44085158/217620862-ab4ca87f-2e05-4a68-bbc8-4dc0e4b2061d.png">

**Comment by soxoj** [comment]
Hey @therealchiendat, sorry for the delay, I'll fix it in the next few days

**Comment by soxoj** [comment]
@therealchiendat, I didn't reproduce your results for FourSquare, Pinterest and Facebook, but fixed them for other sites, please, check master.

**Comment by therealchiendat** [comment]
@soxoj I just pulled your code from master and it worked well! However, the regex check when creating username for `mastodon` is `[a-zA-Z0-9_]+` should we change the regexCheck to match that?

**Comment by soxoj** [comment]
Great! Yeah, I will fix it for all the mastodon instances known in Maigret

**Comment by soxoj** [comment]
Done, I added new regexps! 
So, could I close the issue?

**Comment by therealchiendat** [comment]
Yes! Thank you!
