### ISSUE TITLE
Invalid result https://www.donationalerts.com/r/Skylertheevilbuttdoctor

### ISSUE THREAD

**Issue by MzzPinkP** [soxoj/maigret#869]
Invalid link: https://www.donationalerts.com/r/Skylertheevilbuttdoctor

Put x into the box

[x] ==> [x]

-->

- [x] I'm sure that the link leads to "not found" page

**Comment by MeowyPouncer** [comment]
The given username doesn't surpass the check from here; you might want to update the script.
