### ISSUE TITLE
Invalid result a lot of sites

### ISSUE THREAD

**Issue by eksno** [soxoj/maigret#876]
Invalid link: See screenshot, very obviously fake username leads to tons of false positives. All sites these lead to are less than useful and at the very least should be displayed differently from other results.

![image](https://user-images.githubusercontent.com/33558637/228501063-e92cc536-d87d-4a36-9992-c246796c575c.png)

- [x] I'm sure that the link leads to "not found" page

**Comment by soxoj** [comment]
Thank you, will fix it

**Comment by MeowyPouncer** [comment]
All of the provided sites were taken care of. Closed.
