### ISSUE TITLE
how can i remove progress bar

### ISSUE THREAD

**Issue by luckywaa** [soxoj/maigret#98]
not easy to use
![image](https://user-images.githubusercontent.com/8738803/112968652-14286d80-917f-11eb-8f63-bdaa6ae460a4.png)

**Comment by soxoj** [comment]
There are no such option, but I'll add it, thank you for your feedback.

Could you report what command shell are you using?

**Comment by soxoj** [comment]
I have added `--no-progressbar` option (see #99). Can you update you Maigret installation manually and check that problem was solved?

**Comment by maximousblk** [comment]
Can confirm, no progress bar when using `--no-progressbar`
